#!/bin/sh
#
# @name Typhoon H480 SITL
#
# @type Hexarotor x
#

sh /etc/init.d/rc.mc_defaults

if [ $AUTOCNF = no ]
then
	param set MC_PITCHRATE_P 0.1
	param set MC_ROLLRATE_P 0.1
	param set MC_YAWRATE_P 0.08
	param set MPC_Z_VEL_I 0.15
	param set MPC_Z_VEL_P 0.3
	param set MC_PITCHRATE_MAX 20.0
	param set MC_ROLLRATE_MAX 20.0
	param set MC_YAWRATE_MAX 60.0
	param set MPC_ACC_DOWN_MAX 2
	param set MPC_ACC_HOR 0.5
	param set MPC_ACC_HOR_MAX 2
	param set MPC_ACC_UP_MAX 2
	# param set MPC_XY_VEL_P 0.13
	# param set MPC_XY_VEL_MAX 4

	param set RTL_DESCEND_ALT 5.0
	param set RTL_LAND_DELAY 5

	param set SDLOG_PROFILE 179

	param set OMNI_ATT_MODE 2
	param set OMNI_DFC_MAX_THR 0.20
fi

set MAV_TYPE 13


set MIXER fully_actuated
